CREATE TABLE users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL,password_hash TEXT NOT NULL,salt TEXT NOT NULL,avatar_path TEXT,created_at TEXT);
CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE note_folders(id TEXT PRIMARY KEY, name TEXT,color TEXT,sort REAL, created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT NOT NULL DEFAULT '',demo INTEGER NOT NULL DEFAULT 0);
CREATE TABLE projects(id TEXT PRIMARY KEY, name TEXT,description TEXT,status TEXT,color TEXT,due_date TEXT,progress_cache REAL, created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT NOT NULL DEFAULT '',demo INTEGER NOT NULL DEFAULT 0);
CREATE TABLE notes(id TEXT PRIMARY KEY, title TEXT,content_json TEXT,content_text TEXT,folder_id TEXT,project_id TEXT,tags TEXT,pinned INTEGER,color TEXT,archived INTEGER, created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT NOT NULL DEFAULT '',demo INTEGER NOT NULL DEFAULT 0);
CREATE TABLE tasks(id TEXT PRIMARY KEY, project_id TEXT,title TEXT,description TEXT,status TEXT,priority TEXT,due_date TEXT,assignee_label TEXT,sort REAL,completed_at TEXT, created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT NOT NULL DEFAULT '',demo INTEGER NOT NULL DEFAULT 0);
CREATE TABLE subtasks(id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,title TEXT,done INTEGER, created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT NOT NULL DEFAULT '',demo INTEGER NOT NULL DEFAULT 0);
CREATE TABLE time_entries(id TEXT PRIMARY KEY, task_id TEXT,project_id TEXT,started_at TEXT,ended_at TEXT,seconds INTEGER, created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT NOT NULL DEFAULT '',demo INTEGER NOT NULL DEFAULT 0);
CREATE TABLE events(id TEXT PRIMARY KEY, title TEXT,description TEXT,start_at TEXT,end_at TEXT,all_day INTEGER,color TEXT,remind_before_min INTEGER,project_id TEXT,recurrence_rule TEXT, created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT NOT NULL DEFAULT '',demo INTEGER NOT NULL DEFAULT 0);
CREATE TABLE accounts(id TEXT PRIMARY KEY, name TEXT,type TEXT,currency TEXT,balance_initial REAL, created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT NOT NULL DEFAULT '',demo INTEGER NOT NULL DEFAULT 0);
CREATE TABLE categories(id TEXT PRIMARY KEY, name TEXT,type TEXT,color TEXT, created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT NOT NULL DEFAULT '',demo INTEGER NOT NULL DEFAULT 0);
CREATE TABLE invoices(id TEXT PRIMARY KEY, number TEXT,client_name TEXT,company TEXT,project_id TEXT,status TEXT,issue_date TEXT,due_date TEXT,paid_at TEXT,currency TEXT,notes TEXT, created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT NOT NULL DEFAULT '',demo INTEGER NOT NULL DEFAULT 0);
CREATE TABLE invoice_items(id TEXT PRIMARY KEY, invoice_id TEXT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,title TEXT,amount REAL CHECK(amount >= 0), created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT NOT NULL DEFAULT '',demo INTEGER NOT NULL DEFAULT 0);
CREATE TABLE transactions(id TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(id),to_account_id TEXT,type TEXT,amount REAL CHECK(amount >= 0),category_id TEXT,date TEXT,note TEXT,project_id TEXT,invoice_id TEXT, created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT NOT NULL DEFAULT '',demo INTEGER NOT NULL DEFAULT 0);
CREATE INDEX tasks_project ON tasks(project_id,status);
CREATE INDEX events_start ON events(start_at);
CREATE INDEX transactions_date ON transactions(account_id,date);
CREATE UNIQUE INDEX invoice_payment ON transactions(invoice_id) WHERE invoice_id <> '' AND deleted_at='';
CREATE INDEX notes_updated ON notes(updated_at);
